services:
  db:
    image: postgres:16-alpine
    container_name: minierp_db
    environment:
      POSTGRES_DB: minierp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - minierp_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d minierp"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: minierp_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/minierp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_JWT_SECRET: ${APP_JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

volumes:
  minierp_db_data:
